export const SUPPORTED_LANGUAGES = [
    'Indonesian',
    'English (US)',
    'English (UK)',
    'Japanese',
    'Korean',
    'Thai',
    'Vietnamese',
    'Mandarin (Simplified)',
    'Mandarin (Traditional)',
    'Dutch',
    'German',
    'French',
    'Portuguese (Brazil)',
    'Spanish',
    'Spanish (Latin America)',
    'Swedish',
    'Greek',
    'Bulgarian',
    'Czech',
    'Danish',
    'Finnish',
    'Hungarian',
    'Croatian',
    'Lithuanian',
    'Norwegian (Bokmål)',
    'Polish',
    'Romanian',
    'Russian',
    'Ukrainian',
    'Hindi',
    'Turkish',
];

// Mapping to locale codes for internal use (can be expanded)
export const LANGUAGE_MAP = {
    Indonesian: 'id',
    'English (US)': 'en-US',
    'English (UK)': 'en-GB',
    Japanese: 'ja',
    Korean: 'ko',
    Thai: 'th',
    Vietnamese: 'vi',
    'Mandarin (Simplified)': 'zh-CN',
    'Mandarin (Traditional)': 'zh-TW',
    Dutch: 'nl',
    German: 'de',
    French: 'fr',
    'Portuguese (Brazil)': 'pt-BR',
    Spanish: 'es',
    'Spanish (Latin America)': 'es-419',
    Swedish: 'sv',
    Greek: 'el',
    Bulgarian: 'bg',
    Czech: 'cs',
    Danish: 'da',
    Finnish: 'fi',
    Hungarian: 'hu',
    Croatian: 'hr',
    Lithuanian: 'lt',
    'Norwegian (Bokmål)': 'nb',
    Polish: 'pl',
    Romanian: 'ro',
    Russian: 'ru',
    Ukrainian: 'uk',
    Hindi: 'hi',
    Turkish: 'tr',
};
